
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.web: ERROR
    ru.leodev: DEBUG
  pattern:

    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:\java\Java_School_MMS\src\main\resources\app.log
server:
  port: 8088