
server:
  servlet:
    context-path:  /api/v1
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


