server:
  port: 8088
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mms
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: aleksandrtreskov1@gmail.com
    password: nclkkqjweyxyvuip
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  social:
    facebook:
      appID:
      appSecret:

logging:
  level:
    org.springframework.web: ERROR
    ru.leodev: DEBUG
  pattern:

    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:\java\Java_School_MMS\src\main\resources\app.log
twilio:
  account_sid: ACfff4aa5e66ed399049e77ccce6784671
  auth_token: f0ede3bf58e5b238b03e9cc73a9a90ed
  trial_number: +15076985516
